language: node_js
node_js:
  - 14

dist: xenial

addons:
  sonarcloud:
    organization: "pchmn"

services:
  - docker  

stages:
  - build
  - test
  - name: sonar
    branches:
      only: develop
  - name: deploy
    branches:
      only:
      - main
      - develop

# Skip npm install before each stage
install: true

jobs:
  include:
    # BUILD
    - stage: build
      script:
        - npm i 
        - npm run build
      workspaces:
        # Upload node_modules and dist folder
        create:
          name: dependencies
          paths: 
            - node_modules
            - dist

    # TEST
    - stage: test
      workspaces:
        # Donwload dependencies
        use: dependencies
        # Upload coverage info
        create:
          name: coverage
          paths: coverage/lcov.info
      script: npm run test:cov

    # SONAR
    - stage: sonar
      workspaces:
        # Donwload coverage info
        use: coverage
      script: 
        - sonar-scanner    

    # DEPLOY
    - stage: deploy
      workspaces:
        # Donwload dependencies
        use: dependencies
      before_script:
        # Export env variables according to git branch
        - export NODE_ENV=$(if [${TRAVIS_BRANCH} = "main"]; then echo "production"; else echo "dev"; fi)
        - export SERVICE_ENV=$(if [${TRAVIS_BRANCH} = "main"]; then echo ""; else echo "-dev"; fi)  
      script: 
        # Install aws cli
        - pip install --upgrade pip
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin
        # Login to docker hub
        - echo ${DOCKER_HUB_PWD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
        # Build and push docker image
        - docker build --build-arg NODE_ENV=${NODE_ENV} -t pchmn/la-danze-en-ldc-auth-api . 
        - docker push pchmn/la-danze-en-ldc-auth-api:latest
        # Update aws ecs service to use latest container image
        - aws ecs update-service --cluster ${CLUSTER_NAME} --service ${SERVICE_NAME}${SERVICE_ENV} --force-new-deployment --region ${REGION_NAME}