language: node_js
node_js:
  - 14

dist: xenial

addons:
  sonarcloud:
    organization: "pchmn"

services:
  - docker  

stages:
  - build
  - test
  - name: sonar
    if: branch = develop
  - name: deploy
    if: tag IS present OR branch =~ /^feature.*$/

# Skip npm install before each stage
install: true

jobs:
  include:
    # BUILD
    - stage: build
      script:
        - npm i 
        - npm run build
      workspaces:
        # Upload node_modules and dist folder
        create:
          name: dependencies
          paths: 
            - node_modules
            - dist

    # TEST
    - stage: test
      workspaces:
        # Donwload dependencies
        use: dependencies
        # Upload coverage info
        create:
          name: coverage
          paths: coverage/lcov.info
      script: npm run test:cov

    # SONAR
    - stage: sonar
      workspaces:
        # Donwload coverage info
        use: coverage
      script: 
        - sonar-scanner    

    # DEPLOY
    - stage: deploy
      workspaces:
        # Donwload dependencies
        use: dependencies
      before_script:
        # Export env variables
        - export NODE_ENV=$(if [${TRAVIS_BRANCH} = "main"]; then echo "production"; else echo "dev"; fi)
        - export ECS_ENV=$(if [${TRAVIS_BRANCH} = "main"]; then echo ""; else echo "-dev"; fi)
        - export IMAGE_TAG=$(if [-n ${TRAVIS_TAG}]; then echo ${TRAVIS_TAG}; else echo "latest"; fi)
        - export SERVICE_NAME="auth-api${ECS_ENV}"
        - export TASK_FAMILY=${SERVICE_NAME}
      script: 
        - sh deploy.sh